'use client';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import Head from 'next/head';
import { useAccount, useProvider } from 'wagmi';
import styles from '../styles/Home.module.css';
import dynamic from 'next/dynamic';

const Home = () => {
  const account = useAccount();

  return (
    <div>
      <Head>
        <title>rainbowkit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ConnectButton />
      <div>
        {account.isConnected && `Account ${account.address} is now connected!`}
      </div>
    </div>
  );
};

export default Home;
